//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarringtonDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStateMaster
    {
        public tblStateMaster()
        {
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public string StateCode { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
