//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarringtonDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRequest
    {
        public tblUserRequest()
        {
            this.tblDocRepositories = new HashSet<tblDocRepository>();
            this.tblRequestStatus = new HashSet<tblRequestStatu>();
        }
    
        public long RequestId { get; set; }
        public string RequestNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<long> ZipCode { get; set; }
        public string CityName { get; set; }
        public Nullable<int> StateId { get; set; }
        public string PrimaryPhoneNo { get; set; }
        public string PrimaryPhoneType { get; set; }
        public string PrimaryMobileProvider { get; set; }
        public string SecondaryPhoneNo { get; set; }
        public string SecondaryPhoneType { get; set; }
        public string SecondaryMobileProvider { get; set; }
        public string EmailId { get; set; }
        public string PrefContactMethod { get; set; }
        public string ProblemLocation { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string AttachedDocName { get; set; }
        public Nullable<bool> EmailConfirmation { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<tblDocRepository> tblDocRepositories { get; set; }
        public virtual ICollection<tblRequestStatu> tblRequestStatus { get; set; }
    }
}
