//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarringtonDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public long UserID { get; set; }
        public string EmailId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string CityName { get; set; }
        public Nullable<int> StateId { get; set; }
        public string PrimaryPhoneNo { get; set; }
        public string PrimaryPhoneType { get; set; }
        public string PrimaryMobileProvider { get; set; }
        public string SecondaryPhoneNo { get; set; }
        public string SecondaryPhoneType { get; set; }
        public string SecondaryMobileProvider { get; set; }
        public string PrefferedContactMethod { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string PinNo { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual tblStateMaster tblStateMaster { get; set; }
    }
}
