//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarringtonDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheThinkerz_WTPSharePointEntities : DbContext
    {
        public TheThinkerz_WTPSharePointEntities()
            : base("name=TheThinkerz_WTPSharePointEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tblCityMaster> tblCityMasters { get; set; }
        public DbSet<tblDocRepository> tblDocRepositories { get; set; }
        public DbSet<tblLoginHistory> tblLoginHistories { get; set; }
        public DbSet<tblRequestStatu> tblRequestStatus { get; set; }
        public DbSet<tblStateMaster> tblStateMasters { get; set; }
        public DbSet<tblUserRequest> tblUserRequests { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    }
}
